### ISSUE TITLE
Lens not "magnifying" with some images

### ISSUE THREAD

**Issue by salvatorecapolupo** [marcaube/bootstrap-magnify#9]
Hi,

I am using your library for magnifying a photo gallery in WordPress, but I got a problem because working on very variable widths/heights for my images. So, as a result, some of them would not be magnyfied as well. 

For example, this works very well with a photo 1200x800, but looks not so fine when I magnify a 800x600 one.

Is there a way to enable / disable effect at run-time (switching data-toggle="magnify", if possible), i.e. after checking width/height of current image? 

What is the "minimal" size for having a good zoom effect without affecting responsiveness?

**Comment by marcaube** [comment]
The zoom level depends on the ratio between the size of the image and the size of its container. As such, having same-size images will help have a uniform effect

If you only want to enable magnification on certain images, you should add the data attribute to those images only. You could also skip the data attribute and enable the effect in javascript using `$('.img-class-to-magnify').magnify();`.

There is no method right now to disable the effect, but pull requests are welcome :stuck_out_tongue:

**Comment by salvatorecapolupo** [comment]
Great, I think will crop all of them via server then.

Will try to get disable issue if I can ;)
